
## install dependencies

# forge install foundry-rs/forge-std
# forge install foundry-rs/ds-test

[profile.default]
src = 'contracts'
out = 'out'
script = 'scripts'
libs = ['node_modules', 'lib']
test = 'test'
solc = "0.8.9"
cache_path  = 'forge-cache'

fs_permissions = [{ access = "read-write", path = "./"}]

# eth-rpc-url = "http://localhost:38545"

remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@openzeppelin-upgradable/=node_modules/@openzeppelin/',
  'forge-std/=lib/forge-std/src/',
]

gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
